from ..exceptions import Error


class DiscoveryError(Error):
    """An error raised during discovery."""
